### ISSUE TITLE
TASM Version Help

### ISSUE THREAD

**Issue by flamendless** [leonardo-ono/Assembly8086MarioMusicOnPCSpeakerTest#1]
Hi, really need your input on this one, I'm making one for tasm [here](https://gist.github.com/flamendless/71fe442ae57cae69aeb545cba6b84123)

I get this error though on line `mov bl, [mario_music + si]` (`Operand types do not match`)

Thanks a lot!

**Comment by flamendless** [comment]
It's okay now, I should use 
`label mario_music byte`

**Comment by leonardo-ono** [comment]
sorry for the late reply ! i think you already solved it yourself :)

**Comment by flamendless** [comment]
Hi, yeah it is working with the mario frequency table and music you've provided. However, when I am using another midi and extracted the music data using your java files in this repo as well, it does not play correctly. I need your help on this one. Thanks!
