### ISSUE TITLE
MIDI to frequency doesnt play with the assembly

### ISSUE THREAD

**Issue by flamendless** [leonardo-ono/Assembly8086MarioMusicOnPCSpeakerTest#2]
Hi, yeah it is working with the mario frequency table and music you've provided. However, when I am using another midi and extracted the music data using your java files in this repo as well, it does not play correctly. I need your help on this one. Thanks!

Here is the updated link btw to my code https://gist.github.com/flamendless/71fe442ae57cae69aeb545cba6b84123 

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flamendless** [comment]
Hmm after more research, i think because the way you coded your midi extractor is specific to the mario midi you used, may I know where you got that?

Also, how would we tweak your midi extractor to be for general purpose that can work properly with other midi files?

**Comment by leonardo-ono** [comment]
@flamendless really sorry for the late reply again. i was trying to finish another project ^^'
yes, if i remember correctly, you need to select only one track that you want to extract.
i couldn't test but can you try something like:
...
...
...
       int maxTracks = sequence.getTracks().length;

        // original code -> maxTracks = 2;
        maxTracks = 1;

        for (int t = 0; t < maxTracks; t++) {

//original code -> Track track = sequence.getTracks()[t];
Track track = sequence.getTracks()[ <replace with desired track no.>];

hope this works :)

**Comment by flamendless** [comment]
Yes, i found that out. Apparently some midi i tested didn't work though the track is correct. :/ anyways my assembly project is now finished. Thanks!
